In [46]:
import pandas as pd
import numpy as np
import requests
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

url="https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/groceries.csv"

text=requests.get(url).text
transact = [line.split(",") for line in text.split("\n")]

data= pd.DataFrame(transact)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
data = data.fillna('')

transactions = data.values.tolist()
transactions = [[item for item in row if item != ''] for row in transactions]

print(transactions[:5])

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'], ['tropical fruit', 'yogurt', 'coffee'], ['whole milk'], ['pip fruit', 'yogurt', 'cream cheese ', 'meat spreads'], ['other vegetables', 'whole milk', 'condensed milk', 'long life bakery product']]

In [48]:
te = TransactionEncoder()
te_data = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_data, columns=te.columns_)

print("one-hot encoded DataFrame:")
df.head()

one-hot encoded DataFrame:

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [49]:
freuquent_itemsets = apriori(df, min_support=0.01, use_colnames=True)

print("Frequent Itemsets:")
freuquent_itemsets.sort_values(by='support', ascending=False).head(10)

Frequent Itemsets:

     support                       itemsets
86  0.255490        frozenset({whole milk})
55  0.193473  frozenset({other vegetables})
66  0.183916        frozenset({rolls/buns})
75  0.174359              frozenset({soda})
87  0.139488            frozenset({yogurt})
6   0.110512     frozenset({bottled water})
67  0.108987   frozenset({root vegetables})
81  0.104921    frozenset({tropical fruit})
73  0.098516     frozenset({shopping bags})
70  0.093941           frozenset({sausage})

In [50]:
rules = association_rules(freuquent_itemsets, metric="confidence", min_threshold=0.1)
strong_rules =  rules[(rules['lift']>1) & (rules['confidence']>0.5)]


print('\nStrong Association Rules: ')

strong_rules.head(10)

Strong Association Rules:

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
335,"frozenset({other vegetables, butter})",frozenset({whole milk}),0.020028,0.255490,0.011488,0.573604,2.245113,1.0,0.006371,1.746053,0.565923,0.043512,0.427280,0.309285
339,"frozenset({root vegetables, citrus fruit})",frozenset({other vegetables}),0.017690,0.193473,0.010370,0.586207,3.029916,1.0,0.006948,1.949107,0.682023,0.051646,0.486945,0.319903
351,"frozenset({yogurt, curd})",frozenset({whole milk}),0.017283,0.255490,0.010065,0.582353,2.279357,1.0,0.005649,1.782629,0.571151,0.038313,0.439031,0.310874
354,"frozenset({domestic eggs, other vegetables})",frozenset({whole milk}),0.022265,0.255490,0.012302,0.552511,2.162556,1.0,0.006613,1.663752,0.549826,0.046342,0.398949,0.300331
367,"frozenset({other vegetables, pip fruit})",frozenset({whole milk}),0.026129,0.255490,0.013522,0.517510,2.025557,1.0,0.006846,1.543057,0.519893,0.050436,0.351936,0.285217
375,"frozenset({root vegetables, rolls/buns})",frozenset({other vegetables}),0.024298,0.193473,0.012200,0.502092,2.595154,1.0,0.007499,1.619832,0.629974,0.059347,0.382652,0.282575
385,"frozenset({root vegetables, tropical fruit})",frozenset({other vegetables}),0.021045,0.193473,0.012302,0.584541,3.021306,1.0,0.008230,1.941292,0.683400,0.060835,0.484879,0.324062
414,"frozenset({other vegetables, whipped/sour cream})",frozenset({whole milk}),0.028874,0.255490,0.014640,0.507042,1.984587,1.0,0.007263,1.510292,0.510867,0.054278,0.337876,0.282172
421,"frozenset({other vegetables, yogurt})",frozenset({whole milk}),0.043412,0.255490,0.022265,0.512881,2.007439,1.0,0.011174,1.528393,0.524628,0.080485,0.345718,0.300014
426,"frozenset({root vegetables, rolls/buns})",frozenset({whole milk}),0.024298,0.255490,0.012708,0.523013,2.047096,1.0,0.006500,1.560859,0.524241,0.047583,0.359327,0.286377